### ISSUE TITLE
Get Fail from api

### ISSUE THREAD

**Issue by carlosdurban** [MaxGfeller/youtube-mp3#1]
Hi, i get this error, Fail from api: $$$ERROR$$$

Thanks

**Comment by MaxGfeller** [comment]
Can you provide some additional details? Can you share the youtube-link you're trying to download?

**Comment by carlosdurban** [comment]
Hi Max, i try to download this vid 

https://www.youtube.com/watch?v=GV7YgXl4f_A

Its a golf vid, not music vid. 

I debuggin the code and I found the method that fails. 

pingItem.bind (this),

**Comment by parties** [comment]
Using the demo code I also received an error:

``` html
Fail from api:
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/errors/logo_sm_2.png) no-repeat}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/errors/logo_sm_2_hr.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:55px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
```

**Comment by MaxGfeller** [comment]
Oops, apparently the API changed a little. Does anyone have time to take a look at it? Else i'll investigate it when i find time.

**Comment by geirman** [comment]
I'll take a look at this, but I'll first need some help getting this setup. I'm not clear how to get all the require() statements to work. If you can help me get setup with a working demo, I'll dig in.

Sorry for being such a n00b, but right now these the following is magic to me...
var mp3 = require('youtube-mp3');
var http = require('follow-redirects').http;
var test = require('net');
var runnel = require('runnel');
var fs = require('fs');

**Comment by MaxGfeller** [comment]
@geirman This module is intended to work with [node.js](https://nodejs.org) and probably won't run in the browser. The only way to get it working in the browser would be [browserify](https://browserify.org). But due to the Same-Origin-Policy this probably wouldn't work.

**Comment by geirman** [comment]
Good to know... Thx. How do I get it running with node then, as designed?

**Comment by MaxGfeller** [comment]
Basically it should run like in [Usage](https://github.com/MaxGfeller/youtube-mp3#usage) described.

**Comment by geirman** [comment]
How do I setup for that code to execute though? If you can point me to an
article or describe the basic steps, I'll try figuring it out. Just a
little nudge in the right direction would be helpful... I want to learn

**Comment by MaxGfeller** [comment]
Alright, just install node.js and then do this:

```
mkdir yt-mp3-test
cd yt-mp3-test
npm i youtube-mp3
```

and then copy the example code into a `test.js` file and execute it: `node test.js`

**Comment by nubpro** [comment]
i believe they have their api changed again.
Would you still provide an update?

**Comment by robcalcroft** [comment]
Second to this ^

**Comment by MaxGfeller** [comment]
I'll look into it as soon as i find the time to. Sorry, really busy at the moment.

Anyone up for a pull request?

**Comment by bayfatih2000** [comment]
Hello

I looked new algorithm last week. For example,

1) http://www.youtube-mp3.org/a/pushItem/?item=http%3A//www.youtube.com/watch%3Fv%3DKMU0tzLwhbE&el=na&bf=false&r=1426273141083&s=69554

Result -> KMU0tzLwhbE (youtube video id) I cannot understand s parameter. (r is timestamp and other parameters are constant)

2) http://www.youtube-mp3.org/a/itemInfo/?video_id=KMU0tzLwhbE&ac=www&t=grp&r=1426273141399&s=181714

Result -> info = {"status": "serving", "h2": "88f00ec27752bc7311c6c59584e38e71", "image": "http://i.ytimg.com/vi/KMU0tzLwhbE/default.jpg", "progress_speed": "", "ads": "", "title": "Developers", "h": "1cbcf5457df2d912f77b58e1e86b67b0", "px": "", "ts_create": "1426273141", "length": "3", "r": "ODguMjQxLjIzNC4yNg==", "pf": "", "progress": ""}; 

Again I cannot understand s parameter.

3) http://www.youtube-mp3.org/get?video_id=KMU0tzLwhbE&ts_create=1426273141&r=ODguMjQxLjIzNC4yNg%3D%3D&h2=88f00ec27752bc7311c6c59584e38e71&s=31453

MP3 files can be downloaded by using this URL. Of course again I cannot understand s parameter.

If anyone understand and explain s parameter, I think we can update the source code.

Thank you

**Comment by dylanmensaert** [comment]
It is not difficult to find out. Just beautify the Javascript code, which will give you below code snippets.

I suggest copying the necessary functions, unless you would like to figure out the logic behind  `_sig`.

**url**
    `var b = "/a/pushItem/?item=" + escape(g("youtube-url").value) + "&el=na&bf=" + getBF() + "&r=" + a.getTime(),
        b = sig_url(b);`

**sig_url**
`sig_url = function(a) {
    var b = sig(a);
    return a + "&s=" + escape(b)
};`

**sig**
`sig = function(a) {
    if ("function" == typeof _sig) {
        var b = "X";
        try {
            b = _sig(a)
        } catch (c) {}
        if ("X" != b) return b
    }
    return "-1"
};`

**_sig**
`_sig = function(H) {
    var U = "R3",
        m3 = "round",
        e3 = "B3",
        D3 = "v3",
        N3 = "I3",
        g3 = "V",
        K3 = "toLowerCase",
        n3 = "substr",
        z3 = "Z",
        d3 = "C",
        P3 = "O",
        x3 = ['a', 'c', 'e', 'i', 'h', 'm', 'l', 'o', 'n', 's', 't', '.'],
        G3 = [6, 7, 1, 0, 10, 3, 7, 8, 11, 4, 7, 9, 10, 8, 0, 5, 2],
        M = ['a', 'c', 'b', 'e', 'd', 'g', 'm', '-', 's', 'o', '.', 'p', '3', 'r', 'u', 't', 'v', 'y', 'n'],
        X = [
            [17, 9, 14, 15, 14, 2, 3, 7, 6, 11, 12, 10, 9, 13, 5],
            [11, 6, 4, 1, 9, 18, 16, 10, 0, 11, 11, 8, 11, 9, 15, 10, 1, 9, 6]
        ],
        A = {
            "a": 870,
            "b": 906,
            "c": 167,
            "d": 119,
            "e": 130,
            "f": 899,
            "g": 248,
            "h": 123,
            "i": 627,
            "j": 706,
            "k": 694,
            "l": 421,
            "m": 214,
            "n": 561,
            "o": 819,
            "p": 925,
            "q": 857,
            "r": 539,
            "s": 898,
            "t": 866,
            "u": 433,
            "v": 299,
            "w": 137,
            "x": 285,
            "y": 613,
            "z": 635,
            "_": 638,
            "&": 639,
            "-": 880,
            "/": 687,
            "=": 721
        },
        r3 = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
    gs = function(I, B) {
        var P = "D",
            J = "";
        for (var R = 0; b0I[P](R, I.length); R++) {
            J += B[I[R]];
        };
        return J;
    };
    ew = function(I, B) {
        var P = "K",
            J = "indexOf";
        return I[J](B, b0I[P](I.length, B.length)) !== -1;
    };
    gh = function() {
        var I = gs(G3, x3);
        return eval(I);
    };
    fn = function(I, B) {
        var P = "E",
            J = "G";
        for (var R = 0; b0I[J](R, I.length); R++) {
            if (b0I[P](I[R], B)) return R;
        }
        return -1;
    };
    var L = [1.23413, 1.51214, 1.9141741, 1.5123114, 1.51214, 1.2651],
        F = 1;
    try {
        F = L[b0I[P3](1, 2)];
        var W = gh(),
            S = gs(X[0], M),
            T = gs(X[1], M);
        if (ew(W, S) || ew(W, T)) {
            F = L[1];
        } else {
            F = L[b0I[d3](5, 3)];
        }
    } catch (I) {};
    var N = 3219;
    for (var Y = 0; b0I[z3](Y, H.length); Y++) {
        var Q = H[n3](Y, 1)[K3]();
        if (fn(r3, Q) > -1) {
            N = N + (b0I[g3](parseInt(Q), 121, F));
        } else {
            if (b0I[N3](Q, A)) {
                N = N + (b0I[D3](A[Q], F));
            }
        }
        N = b0I[e3](N, 0.1);
    }
    N = Math[m3](b0I[U](N, 1000));
    return N;
};`

**Comment by dylanmensaert** [comment]
I believe it became impossible to use this service.
Received error: 'Forbidden'. 

They probably check the Host request header to validate the request's origin. There ain't a browser that allows setting the Host header.

**Comment by mandazi** [comment]
I also got this error when I tried it with the example code.

**Comment by dylanmensaert** [comment]
This repository has not been updated for over a year.

###### For any future references, here is my working example:

Copy this whole file and replace `export default` with `return` or any `var` assignment:
https://github.com/dylanmensaert/audio-app/blob/master/app/utils/yt-mp3.js#L168

_Note:_
- use youtube API to get `YOUR_VIDEO_ID` based on input text: https://developers.google.com/apis-explorer/#search/youtube%20search%20list/m/youtube/v3/youtube.search.list
- ytMp3 references the object returned in copied file

I use Ember, so  especially for you guys, I converted my code to jquery:

```
    function signateUrl(url) {
        var host = 'http://www.youtube-mp3.org';

        return host + url + '&s=' + ytMp3.createSignature(host + url);
    }

    var videoId = 'YOUR_VIDEO_ID',
        videoUrl = 'http://www.youtube.com/watch?v=' + videoId,
        url;

    url = '/a/pushItem/?';
    url += 'item=' + escape(videoUrl);
    url += '&el=na&bf=false';
    url += '&r=' + new Date().getTime();

    jQuery.getJSON(signateUrl(url), function(videoId) {
        url = '/a/itemInfo/?';
        url += 'video_id=' + videoId;
        url += '&ac=www&t=grp';
        url += '&r=' + new Date().getTime();

        jQuery.getJSON(signateUrl(url), function(info) {
            var xhr = new XMLHttpRequest();

            info = info.substring(7, info.length - 1);
            info = JSON.parse(info);

            url = '/get?';
            url += 'video_id=' + videoId;
            url += '&ts_create=' + info.ts_create;
            url += '&r=' + info.r;
            url += '&h2=' + info.h2;

            xhr.open('GET', url, true);
            xhr.responseType = 'arraybuffer';

            xhr.onload = function () {
                var audioBlob = new Blob([response]);

                // TODO: do something with your audioBlob.
            };

            xhr.send();        
        }
    });
```

Original code: https://github.com/dylanmensaert/audio-app/blob/master/app/track/model.js#L64

I did not test the conversion, hopes this helps anyway :)
